name: Dialogues
version: '${project.version}'
main: team.aquatic.studios.Dialogues
api-version: '1.20'
authors: [Sxntido]
description: All rights reserved by Aquatic Studios

commands:
  dialogues:
    description: Dialogos de la Academia